import { createGlobalTheme, createGlobalThemeContract } from "@vanilla-extract/css";

import * as COLORS from "./colors/index.ts";

const ColorsContract = createGlobalThemeContract({
	neutral: {
		1: "neutral-1",
		2: "neutral-2",
		3: "neutral-3",
		4: "neutral-4",
		5: "neutral-5",
		6: "neutral-6",
		7: "neutral-7",
		8: "neutral-8",
		9: "neutral-9",
		10: "neutral-10",
		11: "neutral-11",
		12: "neutral-12",
	},
	primary: {
		1: "primary-1",
		2: "primary-2",
		3: "primary-3",
		4: "primary-4",
		5: "primary-5",
		6: "primary-6",
		7: "primary-7",
		8: "primary-8",
		9: "primary-9",
		10: "primary-10",
		11: "primary-11",
		12: "primary-12",
	},
	success: {
		1: "success-1",
		2: "success-2",
		3: "success-3",
		4: "success-4",
		5: "success-5",
		6: "success-6",
		7: "success-7",
		8: "success-8",
		9: "success-9",
		10: "success-10",
		11: "success-11",
		12: "success-12",
	},
	info: {
		1: "info-1",
		2: "info-2",
		3: "info-3",
		4: "info-4",
		5: "info-5",
		6: "info-6",
		7: "info-7",
		8: "info-8",
		9: "info-9",
		10: "info-10",
		11: "info-11",
		12: "info-12",
	},
	warning: {
		1: "warning-1",
		2: "warning-2",
		3: "warning-3",
		4: "warning-4",
		5: "warning-5",
		6: "warning-6",
		7: "warning-7",
		8: "warning-8",
		9: "warning-9",
		10: "warning-10",
		11: "warning-11",
		12: "warning-12",
	},
	danger: {
		1: "danger-1",
		2: "danger-2",
		3: "danger-3",
		4: "danger-4",
		5: "danger-5",
		6: "danger-6",
		7: "danger-7",
		8: "danger-8",
		9: "danger-9",
		10: "danger-10",
		11: "danger-11",
		12: "danger-12",
	},
});

createGlobalTheme(`:root, [data-theme="light"]`, ColorsContract, {
	neutral: COLORS.NEUTRAL.LIGHT,
	primary: COLORS.PRIMARY.LIGHT,
	success: COLORS.SUCCESS.LIGHT,
	info: COLORS.INFO.LIGHT,
	warning: COLORS.WARNING.LIGHT,
	danger: COLORS.DANGER.LIGHT,
});

createGlobalTheme(`[data-theme="dark"]`, ColorsContract, {
	neutral: COLORS.NEUTRAL.DARK,
	primary: COLORS.PRIMARY.DARK,
	success: COLORS.SUCCESS.DARK,
	info: COLORS.INFO.DARK,
	warning: COLORS.WARNING.DARK,
	danger: COLORS.DANGER.DARK,
});

export { ColorsContract };
